// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7G5PlE9K_ZkyZCQ8AWj-vo_7VivjWEw',
    appId: '1:868697452908:web:1afe0850e76179fd930349',
    messagingSenderId: '868697452908',
    projectId: 'glowante-8eb45',
    authDomain: 'glowante-8eb45.firebaseapp.com',
    storageBucket: 'glowante-8eb45.firebasestorage.app',
    measurementId: 'G-GTZGSF6NZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmcG-xkIES7q-MYLRzdrQtzK8jByx4II4',
    appId: '1:868697452908:android:5529ffc1ebb2eb0f930349',
    messagingSenderId: '868697452908',
    projectId: 'glowante-8eb45',
    storageBucket: 'glowante-8eb45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8u8A7vsrxHSY8bPrwNKwXXPJJ1PlLbLs',
    appId: '1:868697452908:ios:087d4ad5c288c878930349',
    messagingSenderId: '868697452908',
    projectId: 'glowante-8eb45',
    storageBucket: 'glowante-8eb45.firebasestorage.app',
    iosBundleId: 'com.example.blocOnboarding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8u8A7vsrxHSY8bPrwNKwXXPJJ1PlLbLs',
    appId: '1:868697452908:ios:087d4ad5c288c878930349',
    messagingSenderId: '868697452908',
    projectId: 'glowante-8eb45',
    storageBucket: 'glowante-8eb45.firebasestorage.app',
    iosBundleId: 'com.example.blocOnboarding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ7G5PlE9K_ZkyZCQ8AWj-vo_7VivjWEw',
    appId: '1:868697452908:web:6d2c40faaf310258930349',
    messagingSenderId: '868697452908',
    projectId: 'glowante-8eb45',
    authDomain: 'glowante-8eb45.firebaseapp.com',
    storageBucket: 'glowante-8eb45.firebasestorage.app',
    measurementId: 'G-K99WNXWP78',
  );
}
