# Uncomment this line to define a global platform for your project
platform :ios, '16.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  pod 'TensorFlowLiteSwift', :path => '../vendor/tensorflow-src/tensorflow/lite/swift'
  pod 'TensorFlowLiteSwift/Metal', :path => '../vendor/tensorflow-src/tensorflow/lite/swift'
  pod 'TensorFlowLiteSwift/CoreML', :path => '../vendor/tensorflow-src/tensorflow/lite/swift'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete('VALID_ARCHS')
      config.build_settings.delete('VALID_ARCHS[sdk=iphonesimulator*]')

      excluded_archs = config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]']
      next if excluded_archs.nil?

      simulator_exclusions = excluded_archs.to_s.split
      simulator_exclusions << 'arm64' unless simulator_exclusions.include?('arm64')
      simulator_exclusions << 'i386' unless simulator_exclusions.include?('i386')
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] =
        simulator_exclusions.join(' ')
    end
  end

  Dir.glob(File.join(installer.sandbox.root, 'Target Support Files', '**', '*.xcconfig')).each do |xcconfig_path|
    xcconfig = File.read(xcconfig_path)
    xcconfig.gsub!(
      /^EXCLUDED_ARCHS\[sdk=iphonesimulator\*\]\s*=.*arm64.*$/,
      'EXCLUDED_ARCHS[sdk=iphonesimulator*] = i386 arm64'
    )
    xcconfig.gsub!(
      /^EXCLUDED_ARCHS\[sdk=iphonesimulator\*\]\s*=\s*i386\s*$/,
      'EXCLUDED_ARCHS[sdk=iphonesimulator*] = i386 arm64'
    )
    xcconfig.gsub!(/^VALID_ARCHS\[sdk=iphonesimulator\*\]\s*=.*\n/, '')
    File.write(xcconfig_path, xcconfig)
  end
end
